# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

   # strategy:
    #  matrix:
     #   node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies npm install
      run: npm install
    - name: Linter (ESLint) npm run lint
      run: npm run lint
    - name: Formatter (Prettier)
      run: npm run prettier
    - name: Test (Jest) CI=true npm run test
      run: npm run test
      env:
       CI: true
    - name: Build npm run build
      run: npm run build